/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/Weather/forecast': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['WeatherForecast'][]
            'application/json': components['schemas']['WeatherForecast'][]
            'text/json': components['schemas']['WeatherForecast'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/AirQuality/countries/{isoCountryCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          isoCountryCode: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AirQualityCountryResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/AirQuality/locations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          ne_lat?: number | string
          ne_lng?: number | string
          sw_lat?: number | string
          sw_lng?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AirQualityLocationResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AirQualityCountry: {
      /** Format: int64 */
      id: number | string
      code: string
      name: string
      /** Format: date-time */
      dateTimeFirst: null | string
      /** Format: date-time */
      dateTimeLast: null | string
      parameters: components['schemas']['AirQualityParameter'][]
    }
    AirQualityCountryResponse: {
      results: components['schemas']['AirQualityCountry'][]
    }
    AirQualityLocation: {
      /** Format: int64 */
      id: number | string
      name: string
      locality: null | string
      timezone: string
      country: components['schemas']['AirQualityLocationCountry']
      owner: components['schemas']['AirQualityLocationOrganization']
      provider: components['schemas']['AirQualityLocationOrganization']
      isMobile: boolean
      isMonitor: boolean
      instruments: components['schemas']['AirQualityLocationInstrument'][]
      sensors: components['schemas']['AirQualityLocationSensor'][]
      coordinates: components['schemas']['AirQualityLocationCoordinates']
      licenses: components['schemas']['AirQualityLocationLicense'][]
      bounds: (number | string)[]
      /** Format: double */
      distance: null | number | string
      dateTimeFirst: components['schemas']['AirQualityLocationDateTime']
      dateTimeLast: components['schemas']['AirQualityLocationDateTime']
    }
    AirQualityLocationAttribution: {
      name: string
      url: null | string
    }
    AirQualityLocationCoordinates: {
      /** Format: double */
      latitude: number | string
      /** Format: double */
      longitude: number | string
    }
    AirQualityLocationCountry: {
      /** Format: int64 */
      id: number | string
      code: string
      name: string
    }
    AirQualityLocationDateTime: {
      /** Format: date-time */
      utc: string
      /** Format: date-time */
      local: string
    }
    AirQualityLocationInstrument: {
      /** Format: int64 */
      id: number | string
      name: string
    }
    AirQualityLocationLicense: {
      /** Format: int64 */
      id: number | string
      name: string
      attribution: components['schemas']['AirQualityLocationAttribution']
      /** Format: date-time */
      dateFrom: string
      /** Format: date-time */
      dateTo: null | string
    }
    AirQualityLocationMeta: {
      name: string
      website: string
      /** Format: int32 */
      page: number | string
      /** Format: int32 */
      limit: number | string
      /** Format: int32 */
      found?: null | number | string
    }
    AirQualityLocationOrganization: {
      /** Format: int64 */
      id: number | string
      name: string
    }
    AirQualityLocationParameter: {
      /** Format: int64 */
      id: number | string
      name: string
      units: string
      displayName: null | string
    }
    AirQualityLocationResponse: {
      meta: components['schemas']['AirQualityLocationMeta']
      results: components['schemas']['AirQualityLocation'][]
    }
    AirQualityLocationSensor: {
      /** Format: int64 */
      id: number | string
      name: string
      parameter: components['schemas']['AirQualityLocationParameter']
    }
    AirQualityParameter: {
      /** Format: int64 */
      id: number | string
      name: string
      units: string
      displayName: null | string
    }
    ProblemDetails: {
      type?: null | string
      title?: null | string
      /** Format: int32 */
      status?: null | number | string
      detail?: null | string
      instance?: null | string
    }
    WeatherForecast: {
      /** Format: date */
      date: string
      /** Format: int32 */
      temperatureC: number | string
      summary: null | string
      /** Format: int32 */
      temperatureF?: number | string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
