/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/Weather/forecast': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['WeatherForecast'][]
            'application/json': components['schemas']['WeatherForecast'][]
            'text/json': components['schemas']['WeatherForecast'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/Ultraviolet/forecast': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          lat?: number
          lng?: number
          alt?: number
          dt?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UltravioletForecastMetaResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/AirQuality/countries/{isoCountryCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          isoCountryCode: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AirQualityCountryResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/AirQuality/locations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          ne_lat?: number
          ne_lng?: number
          sw_lat?: number
          sw_lng?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AirQualityLocationsResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/AirQuality/sensor/{sensorId}/measurements': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          date_from?: string
          date_to?: string
        }
        header?: never
        path: {
          sensorId: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AirQualityMeasurementsResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AirQualityCountry: {
      /** Format: int64 */
      id: number
      code: string
      name: string
      /** Format: date-time */
      dateTimeFirst: null | string
      /** Format: date-time */
      dateTimeLast: null | string
      parameters: components['schemas']['AirQualityParameter'][]
    }
    AirQualityCountryResponse: {
      results: components['schemas']['AirQualityCountry'][]
    }
    AirQualityLocation: {
      /** Format: int64 */
      id: number
      name: string
      locality: null | string
      timezone: string
      country: components['schemas']['AirQualityLocationCountry']
      owner: components['schemas']['AirQualityLocationOrganization']
      provider: components['schemas']['AirQualityLocationOrganization']
      isMobile: boolean
      isMonitor: boolean
      instruments: components['schemas']['AirQualityLocationInstrument'][]
      sensors: components['schemas']['AirQualityLocationSensor'][]
      coordinates: components['schemas']['AirQualityLocationCoordinates']
      licenses: components['schemas']['AirQualityLocationLicense'][]
      bounds: number[]
      /** Format: double */
      distance: null | number
      dateTimeFirst: components['schemas']['AirQualityLocationDateTime']
      dateTimeLast: components['schemas']['AirQualityLocationDateTime']
    }
    AirQualityLocationAttribution: {
      name: string
      url: null | string
    }
    AirQualityLocationCoordinates: {
      /** Format: double */
      latitude: number
      /** Format: double */
      longitude: number
    }
    AirQualityLocationCountry: {
      /** Format: int64 */
      id: number
      code: string
      name: string
    }
    AirQualityLocationDateTime: {
      /** Format: date-time */
      utc: string
      /** Format: date-time */
      local: string
    }
    AirQualityLocationInstrument: {
      /** Format: int64 */
      id: number
      name: string
    }
    AirQualityLocationLicense: {
      /** Format: int64 */
      id: number
      name: string
      attribution: components['schemas']['AirQualityLocationAttribution']
      /** Format: date-time */
      dateFrom: string
      /** Format: date-time */
      dateTo: null | string
    }
    AirQualityLocationMeta: {
      name: string
      website: string
      /** Format: int32 */
      page: number
      /** Format: int32 */
      limit: number
    }
    AirQualityLocationOrganization: {
      /** Format: int64 */
      id: number
      name: string
    }
    AirQualityLocationParameter: {
      /** Format: int64 */
      id: number
      name: string
      units: string
      displayName: null | string
    }
    AirQualityLocationSensor: {
      /** Format: int64 */
      id: number
      name: string
      parameter: components['schemas']['AirQualityLocationParameter']
    }
    AirQualityLocationsResponse: {
      meta: components['schemas']['AirQualityLocationMeta']
      results: components['schemas']['AirQualityLocation'][]
    }
    AirQualityMeasurement: {
      /** Format: double */
      value: null | number
      parameter: components['schemas']['AirQualityMeasurementParameter']
      period: components['schemas']['AirQualityMeasurementPeriod']
      coordinates: null | components['schemas']['AirQualityMeasurementCoordinates']
      summary: null | components['schemas']['JsonElement']
      coverage: components['schemas']['AirQualityMeasurementCoverage']
    }
    AirQualityMeasurementCoordinates: {
      /** Format: double */
      latitude: number
      /** Format: double */
      longitude: number
    }
    AirQualityMeasurementCoverage: {
      /** Format: int32 */
      expectedCount: number
      expectedInterval: string
      /** Format: int32 */
      observedCount: number
      observedInterval: string
      /** Format: double */
      percentComplete: number
      /** Format: double */
      percentCoverage: number
      dateTimeFrom: components['schemas']['AirQualityMeasurementDateTime']
      dateTimeTo: components['schemas']['AirQualityMeasurementDateTime']
    }
    AirQualityMeasurementDateTime: {
      /** Format: date-time */
      utc: string
      /** Format: date-time */
      local: string
    }
    AirQualityMeasurementMeta: {
      name: string
      website: string
      /** Format: int32 */
      page: number
      /** Format: int32 */
      limit: number
    }
    AirQualityMeasurementParameter: {
      /** Format: int64 */
      id: number
      name: string
      units: string
      displayName: null | string
    }
    AirQualityMeasurementPeriod: {
      label: string
      interval: string
      dateTimeFrom: components['schemas']['AirQualityMeasurementDateTime']
      dateTimeTo: components['schemas']['AirQualityMeasurementDateTime']
    }
    AirQualityMeasurementsResponse: {
      meta: components['schemas']['AirQualityMeasurementMeta']
      results: components['schemas']['AirQualityMeasurement'][]
    }
    AirQualityParameter: {
      /** Format: int64 */
      id: number
      name: string
      units: string
      displayName: null | string
    }
    JsonElement: unknown
    ProblemDetails: {
      type?: null | string
      title?: null | string
      /** Format: int32 */
      status?: null | number
      detail?: null | string
      instance?: null | string
    }
    UltravioletForecastMeta: {
      max: null | components['schemas']['UltravioletForecastResult']
    }
    UltravioletForecastMetaResponse: {
      result: components['schemas']['UltravioletForecastResult'][]
      meta: components['schemas']['UltravioletForecastMeta']
    }
    UltravioletForecastResult: {
      /** Format: double */
      uv: number
      /** Format: date-time */
      uv_time: string
      sun_position: components['schemas']['UltravioletSunPosition']
    }
    UltravioletSunPosition: {
      /** Format: double */
      azimuth: number
      /** Format: double */
      altitude: number
    }
    WeatherForecast: {
      /** Format: date */
      date: string
      /** Format: int32 */
      temperatureC: number
      summary: null | string
      /** Format: int32 */
      temperatureF?: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
